config/routes.rb
Rails.application.routes.draw do
  resources :voisins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
post '/api/new', to: 'api#voisinage'
get '/api/listevoisins', to: 'api#listevoisins'
get '/api/listevoisinsfavoris', to: 'api#listevoisinsfavoris'
get '/api/detailsvoisins/:id', to: 'api#detailsvoisins'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voisin.rb
class Voisin < ApplicationRecord
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
    skip_before_action :verify_authenticity_token
    def voisinage
        voisin = Voisin.new(
            name: params[:name],
            phone: params[:phone],
            address: params[:address],
            about: params[:about],
            favory: params[:favory]
        )
        if voisin.save
            render status:200, json: {message: 'SUCCESS'}
        else
            render status:200, json: {message: 'FAILED'} 
        end
    end
    def listevoisins
        voisin = Voisin.all
        render status:200, json: voisin
    end
    def listevoisinsfavoris
        voisin = Voisin.where(favory: '1').all
        render status:200, json: voisin
    end
    def detailsvoisins
        voisin = Voisin.find(params[:id]) 
        render status:200, json: voisin
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/voisins_controller.rb
class VoisinsController < ApplicationController
  before_action :set_voisin, only: [:show, :edit, :update, :destroy]

  # GET /voisins
  # GET /voisins.json
  def index
    @voisins = Voisin.all
  end

  # GET /voisins/1
  # GET /voisins/1.json
  def show
  end

  # GET /voisins/new
  def new
    @voisin = Voisin.new
  end

  # GET /voisins/1/edit
  def edit
  end

  # POST /voisins
  # POST /voisins.json
  def create
    @voisin = Voisin.new(voisin_params)

    respond_to do |format|
      if @voisin.save
        format.html { redirect_to @voisin, notice: 'Voisin was successfully created.' }
        format.json { render :show, status: :created, location: @voisin }
      else
        format.html { render :new }
        format.json { render json: @voisin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voisins/1
  # PATCH/PUT /voisins/1.json
  def update
    respond_to do |format|
      if @voisin.update(voisin_params)
        format.html { redirect_to @voisin, notice: 'Voisin was successfully updated.' }
        format.json { render :show, status: :ok, location: @voisin }
      else
        format.html { render :edit }
        format.json { render json: @voisin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voisins/1
  # DELETE /voisins/1.json
  def destroy
    @voisin.destroy
    respond_to do |format|
      format.html { redirect_to voisins_url, notice: 'Voisin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voisin
      @voisin = Voisin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def voisin_params
      params.require(:voisin).permit(:name, :phone, :address, :about, :favory)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voisins_helper.rb
module VoisinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projetweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/voisins/_form.html.erb
<%= form_with(model: voisin, local: true) do |form| %>
  <% if voisin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voisin.errors.count, "error") %> prohibited this voisin from being saved:</h2>

      <ul>
        <% voisin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :favory %>
    <%= form.check_box :favory %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/voisins/edit.html.erb
<h1>Editing Voisin</h1>

<%= render 'form', voisin: @voisin %>

<%= link_to 'Show', @voisin %> |
<%= link_to 'Back', voisins_path %>

app/views/voisins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voisins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>About</th>
      <th>Favory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voisins.each do |voisin| %>
      <tr>
        <td><%= voisin.name %></td>
        <td><%= voisin.phone %></td>
        <td><%= voisin.address %></td>
        <td><%= voisin.about %></td>
        <td><%= voisin.favory %></td>
        <td><%= link_to 'Show', voisin %></td>
        <td><%= link_to 'Edit', edit_voisin_path(voisin) %></td>
        <td><%= link_to 'Destroy', voisin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voisin', new_voisin_path %>

app/views/voisins/new.html.erb
<h1>New Voisin</h1>

<%= render 'form', voisin: @voisin %>

<%= link_to 'Back', voisins_path %>

app/views/voisins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @voisin.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @voisin.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @voisin.address %>
</p>

<p>
  <strong>About:</strong>
  <%= @voisin.about %>
</p>

<p>
  <strong>Favory:</strong>
  <%= @voisin.favory %>
</p>

<%= link_to 'Edit', edit_voisin_path(@voisin) %> |
<%= link_to 'Back', voisins_path %>